// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBimc2XPOg8c-FQW0oj2lLGh1qpD6nd3AE',
    appId: '1:989146371366:web:5b5070e83676f2893a9de7',
    messagingSenderId: '989146371366',
    projectId: 'todoapp-6be26',
    authDomain: 'todoapp-6be26.firebaseapp.com',
    storageBucket: 'todoapp-6be26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbjQgaTr6tarf32oiwe9J8Y80uikjjUws',
    appId: '1:989146371366:android:3f30b8f9213d8ac23a9de7',
    messagingSenderId: '989146371366',
    projectId: 'todoapp-6be26',
    storageBucket: 'todoapp-6be26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGdi7HNmMdHHAk7rYyE6_caA1LRB0ozXY',
    appId: '1:989146371366:ios:0cb6627e9c1f7c003a9de7',
    messagingSenderId: '989146371366',
    projectId: 'todoapp-6be26',
    storageBucket: 'todoapp-6be26.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );
}
